apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
spec:
  replicas: 1                      # кількість екземплярів Pod, що буде створено цим Deployment
  selector:
    matchLabels:
      app: service2                # селектор по якому Deployment зв'язаний з Pod
  template:
    metadata:
     labels:
       app: service2               # мітка Pod по якому вона буде зв'язана з Deployment та Service
    spec:
      containers:
        - image: 17090120/service2:latest       # образ Docker
          name: service2           # ім'я контейнеру
          ports:
            - containerPort: 80  # порт по якому можна звертатись до поди