apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - http:
        paths:
          - path: /Home # шлях по якому відбувається перенаправлення на сервіс
            pathType: Prefix # все, що починається з `/api` буде направлено на сервіс demo-service. Альтернативно можна використовувати `Exact` та `ImplementationSpecific`
            backend:
              service:
                name: service1 # ім'я сервісу
                port:
                  number: 80 # порт на якому запущено сервіс
          - path: /Snus
            pathType: Prefix
            backend:
              service:
                name: service2
                port:
                  number: 80
